# Generated by Django 5.1.2 on 2024-10-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_privategroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateGroup',
        ),
    ]
